# Generated by Django 4.2.10 on 2024-08-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("clothing", "Clothing"),
                    ("home", "Home"),
                    ("groceries", "Groceries"),
                    ("health_beauty", "Health & Beauty"),
                    ("toys", "Toys"),
                    ("furniture", "Furniture"),
                    ("sports_outdoors", "Sports & Outdoors"),
                    ("automotive", "Automotive"),
                    ("books_stationery", "Books & Stationery"),
                    ("kitchenware", "Kitchenware"),
                    ("pet_supplies", "Pet Supplies"),
                    ("baby_products", "Baby Products"),
                    ("household_cleaning", "Household Cleaning"),
                ],
                max_length=50,
            ),
        ),
    ]
