# Generated by Django 4.2.10 on 2024-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("clothing", "Clothing"),
                    ("home", "Home"),
                    ("groceries", "Groceries"),
                    ("health_beauty", "Health & Beauty"),
                    ("toys", "Toys"),
                ],
                max_length=50,
            ),
        ),
    ]
