# Generated by Django 4.2.10 on 2024-08-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="media/barcodes/")),
            ],
        ),
    ]
